fix type information when using dinamic projection and generic repository
Cosium/spring-data-jpa-entity-graph pull request #149
Opened 2023-12-25 16:21 UTC by leassis

fix the type information when using generic repository along with dynamic projections.

This PR this [issue](https://github.com/Cosium/spring-data-jpa-entity-graph/issues/148#issue-2055746775).

2023-12-26 13:03 UTC, reda-alaoui commented
Hello @leassis ,
Please fix the formatting issue.

2023-12-26 16:08 UTC, leassis commented
Do you have a standard formatter?

2023-12-26 16:10 UTC, reda-alaoui commented
Yes, [this one](https://github.com/Cosium/git-code-format-maven-plugin)

You can run [this](https://github.com/Cosium/git-code-format-maven-plugin?tab=readme-ov-file#manual-code-formatting) to format your code.

2023-12-26 16:27 UTC, leassis commented
done!

2023-12-26 16:39 UTC, reda-alaoui requested changes
Everything looks fine to me.

But this introduces a breaking change regarding the support of Spring Data JPA. Therefore, the README's Compatibility matrix (https://github.com/Cosium/spring-data-jpa-entity-graph?tab=readme-ov-file#compatibility-matrix) should be changed to show that:
- Spring Data JPA `3.2.1+` is supported by Spring Data JPA Entity Graph `3.2.2+`
- Spring Data JPA `3.2.0` is supported by Spring Data JPA Entity Graph `3.2.0-3.2.1`

2023-12-27 17:26 UTC, reda-alaoui requested changes

2023-12-27 17:26 UTC, reda-alaoui commented on README.md
> +| 3.2.0                                                                         | [![Maven Central 3.2.0](https://img.shields.io/maven-central/v/com.cosium.spring.data/spring-data-jpa-entity-graph/3.
```suggestion
| 3.2.0                                                                         | [![Maven Central 3.2.1](https://img.shields.io/maven-central/v/com.cosium.spring.data/spring-data-jpa-entity-graph/3.2.1.svg)](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.cosium.spring.data%22%20AND%20a%3A%22spring-data-jpa-entity-graph%22) |
```

2023-12-27 17:26 UTC, reda-alaoui commented on README.md
>  | 3.2.x                                                                         | [![Maven Central 3.2.x](https://img.shields.io/maven-central/v/com.cosium.spring.data/spring-data-jpa-entity-graph/3.
```suggestion
```

2023-12-27 17:39 UTC, reda-alaoui approved these changes

2023-12-27 17:40 UTC, merged

2023-12-27 17:40 UTC, reda-alaoui commented
Thank you @leassis !